services:
  web-server:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/project
      - ./env/nginx_default.conf:/etc/nginx/conf.d/default.conf
    networks:
      user-events_net:
        ipv4_address: 172.27.0.2

  user-service:
    image: php:8.4-fpm-alpine
    container_name: user-service
    build: .
    volumes:
      - .:/var/www/project
    ports:
      - '9000:9000'
    networks:
      user-events_net:
        ipv4_address: 172.27.0.4

networks:
  user-events_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1